cloudendpoints/esp

- src/nginx/config.cc
- src/nginx/module.h
The plan is to use server_config directly.   start_esp will create a server_config, and pass the settings from flags to server_config.
> Remove new Nginx config settings.

- WORKSPACE
- src/nginx/main/testdata/copyright-expected
- src/nginx/module.cc
- src/nginx/t/no_service_control.t
- third_party/BUILD
- Removed unused function prototype
- Fix undefined behavior of offset() on non-POD types
- Fix the shutdown timer logic which works on newer NGINX since 1.11.11
> Update NGINX to 1.13.3

- test/bookstore/swagger_template.json
If not empty,  ESP will response with 302 redirect to that URL.  E2E test was not expecting that.
> Make authorizationUrl empty to fix e2e test.

- test/bookstore/gke/nginx.conf
This nginx config file is passed into gke as custom nginx config in custom e2e test.
service_config now is in /etc/nginx/endpoints/server_config.pb.txt
api is not needed. downloaded service config file path is stored in server_config.pb.txt
> fix gke custom e2e test.

- Jenkinsfile
For GCE tests,  GCE has two E2E tests; fixed and managed.  But they both use the same service name.
The tests are run parallel.  when both are trying to deploy a service,   they could step over each other, cause the last step rollout to fail.
> add rollout strategy to the service name.

- src/api_manager/auth/lib/auth_jwt_validator.cc
- src/api_manager/auth/lib/auth_jwt_validator_test.cc
1. Issue description.
According to https://tools.ietf.org/html/rfc7517#page-8, the alg field of JWK keys is optional.
ESP should add the support of JWK keys that do not have the alg field.
2. Issue solution.
esp/src/api_manager/auth/lib/auth_jwt_validator.cc is revised to add the support of JWK keys that do not have the alg field.
3. Testing the solution.
A new test case OkTokenJwkNoAlg is added to esp/src/api_manager/auth/lib/auth_jwt_validator_test.cc to test JWK keys without alg field.
The new test and existing working tests passed.
Note: when running "bazel test //src/... //third_party:all", there were two tests failed: //src/nginx/t:auth_openid and //src/nginx/t:auth_ssl.
These two test failures are not related to this code change. Without this code change, these two test cases still …
> Add the support of JWK keys without the alg field

- script/linux-grpc-test-long-run
grpc test is flaky due to its test client occasionally crashed at
2068 channel_cc.cc:136]          assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)
retry the test if the client is crashed.
> Retry crashed grpc test client.

- src/api_manager/service_control/aggregated.cc
- src/api_manager/service_control/aggregated.h
At exiting,   the Aggregator object may have been freed when Report done callback is called.
To cause following warning.
SUMMARY: ThreadSanitizer: heap-use-after-free src/api_manager/service_control/aggregated.cc:270 operator()
Also add tailing _ for two member variables
> Fix a tsan warning.

- doc/k8s/README.md
- doc/k8s/esp_echo_http.yaml
The endpoints container registry "b.gcr.io/endpoints/endpoints-runtime:0.3" has
been deprecated. In this fix, the deprecated container registry is updated
to the correct endpoints container registry.
> Fix outdated endpoints container registry

- README.md
- doc/build-esp-on-ubuntu-16-04.md
- doc/testing.md
- doc/tutorial.md
1. Add the software packages required for building ESP.
2. Add the software packages required for running ESP tests.
3. Add a step-by-step guide for building ESP on Ubuntu 16.04, and running tests.
> Add packages for ESP building and tests, and ESP building guide on Ubuntu

- script/linux-gae-instance
- script/linux-test-vm-bookstore
- script/linux-test-vm-echo
1. Problem description
With current ESP Jenkins test scripts, ESP Nginx error log is not retrieved and saved when running in the App Engine Flex environment.
2. Solution
This code retrieves ESP Nginx error log and saves it to Cloud Storage when running ESP Jenkins tests in the App Engine Flex environment.
> Retrieve and save ESP Nginx error log in the App Engine Flex environment

- Jenkinsfile
command is overwriting the [entrypoint](https://github.com/cloudendpoints/esp/blob/master/jenkins/slaves/entrypoint) set in the docker image, which starts the docker daemon.
> Force to use the entrypoint

- repositories.bzl
- src/grpc/zero_copy_stream.h
- src/nginx/t/BUILD
- src/nginx/t/transcoding_h2.t
- src/nginx/zero_copy_stream.cc
- src/nginx/zero_copy_stream.h
- remove `pos_` from NgxRequestZeroCopyInputStream
NGINX may parse additional DATA frame into the existing `ngx_buf_t` which `NgxRequestZeroCopyInputStream` is holding, makes `pos_` is in the wrong place in the middle of buffer.
> fix transcoding issue with h2

- src/nginx/http.cc
This PR adds the SNI (Server Name Indication) support to ESP for https clients.
Problem solved by this PR: before this PR, ESP https clients do not support SNI for https connections. Details in the following two github issues.
- https://github.com/cloudendpoints/esp/issues/271
- https://github.com/cloudendpoints/esp/issues/262
> Add SNI support to ESP for https clients

- script/linux-install-software
- src/api_manager/auth/lib/json.cc
- src/api_manager/check_auth_test.cc
- src/nginx/t/auth_pass_user_info.t
- src/nginx/t/grpc_auth_pkey.t
- src/nginx/t/transcoding_metadata.t
Per the request from https://github.com/cloudendpoints/esp/issues/407, add JWT claims to the X-Endpoint-API-UserInfo header.
> Add JWT claims to the X-Endpoint-API-UserInfo header

- src/grpc/proxy_flow.cc
- src/nginx/t/BUILD
- src/nginx/t/grpc_skip_host_header_in_metadata.t
- test/transcoding/bookstore-server.cc
gRPC requests (HTTP2) with a host header will lead some gRPC servers to reject it, so the host header is skipped in the grpc metadata.
> Skip the host header in the grpc metadata

- start_esp/nginx-auto.conf.template
Per http://nginx.org/en/docs/http/ngx_http_headers_module.html, add_header "adds the specified field to a response header provided that the response code equals 200, 201 (1.3.10), 204, 206, 301, 302, 303, 304, 307 (1.1.16, 1.0.13), or 308 (1.13.0)."  This PR always adds the Access-Control-Allow-Origin header regardless of the response code.
> CORS always adds the Access-Control-Allow-Origin header

- src/nginx/grpc_server_call.cc
This PR https://github.com/cloudendpoints/esp/pull/450: add a new function ConvertByteBuffer() which has memory leak.   grpc_slice ref_count is not handled properly.
> Fix memory leak in grpc ConvertByteBuffer

- src/api_manager/BUILD
- src/api_manager/api_manager_impl.cc
- src/api_manager/api_manager_test.cc
- src/api_manager/config_manager.cc
- src/api_manager/config_manager.h
- src/api_manager/config_manager_test.cc
- src/api_manager/utils/BUILD
- src/api_manager/utils/time_based_counter.cc
- src/api_manager/utils/time_based_counter.h
- src/api_manager/utils/time_based_counter_test.cc
ESP is call ServiceManagement service to check its latest rollout in every minute regardless the ESP is idle or not.
In order to reduce the load to ServiceManagement,  it is better not to make these calls for these Idle ESP instances.
> Not checking service management rollouts if not traffic

- src/api_manager/auth/lib/auth_jwt_validator.cc
If not cleared, these SSL errors will show up in the data code path as Nginx alert. which is misleading.
> Clear SSL errors if JWT signature validation fails

- src/api_manager/check_auth_test.cc
- src/api_manager/cloud_trace/cloud_trace.cc
- src/api_manager/cloud_trace/cloud_trace.h
- src/api_manager/cloud_trace/cloud_trace_test.cc
- src/api_manager/context/request_context.cc
The encoding is defined here:
https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/BinaryEncoding.md#trace-context
> Add support for grpc tracing header.

- script/release-publish
We add a new docker image for serverless.  publish script needs to publish it too.
> Update script to publish serverless docker image

- src/grpc/proxy_flow.cc
- src/grpc/proxy_flow.h
- src/grpc/server_call.h
- src/nginx/grpc_server_call.cc
- src/nginx/grpc_server_call.h
- src/nginx/module.h
An attempt to fix #504. 
Currently, when ESP is connected with connection pooling, there is no mechanism to detect network connection issue/error.
> Call TryCancel and StartUpstreamFinish when there is a connection error

- src/api_manager/cloud_trace/BUILD
- src/api_manager/cloud_trace/aggregator.cc
- src/api_manager/cloud_trace/aggregator.h
- src/api_manager/cloud_trace/cloud_trace.cc
- src/api_manager/cloud_trace/cloud_trace.h
- src/api_manager/cloud_trace/sampler.cc
- src/api_manager/cloud_trace/sampler.h
- src/api_manager/cloud_trace/sampler_test.cc
This change allows us to make granular and isolated changes in some of the classes. The cloud_trace.[h|cc] had a lot of logic inside.
This PR does not contain any changes in the current logic, only code moved to smaller files.
> Split cloud_trace.[h|cc] into sampler/aggregator/cloud_trace.

- docker/serverless/env-start-esp.py
The 'SERVICE_NAME' variable is renamed 'ENDPOINTS_SERVICE_NAME' for
clarity. 'ENDPOINTS_SERVICE_VERSION' is a new optional env variable
which changes rollout strategy to fixed and specifies the version.
'CORS_PRESET' is a new optional env variable for the CORS preset
command line option. Also, 'ESP_ARGS' supports specifying a delimiter
other than the comma; this works the same way as in gcloud.
> Improve env variable handling in serverless image startup script.

- docker/serverless/env-start-esp.py
The script was catching the wrong exception class (`ValueError` instead of `KeyError`), but this new approach is easier to read anyway.
> Fix exception handling in serverless startup script.

- doc/testing.md
- doc/tutorial.md
* doc/testing.md: On macOS/OS X, attempting to use `bazel build` may
fail due to an `expected identifier` caused by Bazel sending the
`DEBUG` directive.  Using `bazel build -c opt` works around this issue.
* doc/tutorial.md: Same as above
> doc: use optimized build if DEBUG directive causes build failure

- src/nginx/grpc_web_finish.cc
Whenever building on macOS/OS X, the following would happen:
```
src/nginx/grpc_web_finish.cc:235:7: error: no matching function for call to 'EncodesGrpcStatusCode'
EncodesGrpcStatusCode(r, status.CanonicalCode(), &length);
^~~~~~~~~~~~~~~~~~~~~
src/nginx/grpc_web_finish.cc:93:14: note: candidate function not viable: no known conversion from 'uint64_t *' (aka 'unsigned long long *') to 'size_t *' (aka 'unsigned long *') for 3rd argument
ngx_chain_t *EncodesGrpcStatusCode(ngx_http_request_t *r, const Code &code,
^
src/nginx/grpc_web_finish.cc:241:20: error: no matching function for call to 'EncodesGrpcMessage'
grpc_message = EncodesGrpcMessage(r, status.message(), &length);
^~~~~~~~~~~~~~~~~~
src/nginx/grpc_web_finish.cc:117:14: note: candidate function not viable: no known conversion from …
```
> nginx: fix type mismatch during compilation on macOS/OS X

- src/nginx/grpc_passthrough_server_call.cc
- src/nginx/grpc_passthrough_server_call.h
- src/nginx/grpc_server_call.cc
- src/nginx/grpc_server_call.h
- src/nginx/transcoded_grpc_server_call.cc
- src/nginx/transcoded_grpc_server_call.h
This is to fix https://github.com/cloudendpoints/esp/issues/550
Create a free buffer list for re-cycle.  After a response buffer is written, the buffers are put into the free list in line 762, file src/nginx/grpc_server_call.cc
We keep re-using the largest buffer, if a buffer is too small, create a new one with a bigger size.
But only grpc pass through is using the buffer from re-cycle list since it may be long live streaming.
Transcoding buffer usage is different, and complicated. Beside it only has request/response, so its buffer usage is fine, not need to recycle it.
> Fix grpc stream memory leak by re-cycle buffers

- docker/serverless/env-start-esp.py
When possible, start a simple HTTP server to serve 503 Service Unavailable with the error message.
> Exception fixes in serverless startup script

- script/linux-grpc-test-long-run
- src/nginx/grpc_server_call.cc
In some error cases,  request r could be gone before grpc server_call is deleted by grpc proxy_flow.
Also check http stream failure in e2e tests.  That is why this crash was not detected by e2e tests.
> Fix a crash from fuzz tests

- .bazelrc
- src/nginx/t/ApiManager.pm
When attempting to run the unit tests on macOS/OS X, the build process would typically fail due to something like this:
```
ERROR: /private/var/tmp/_bazel_notyou/78403766dcde049347f91d5e087e2902/external/com_github_grpc_grpc/BUILD:1556:1: Linking of rule '@com_github_grpc_grpc//:grpc_transport_chttp2' failed (Exit 1).
13ld: illegal thread local variable reference to regular symbol __ZN9grpc_core7ExecCtx9exec_ctx_E for architecture x86_64
14clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Basically, the issue is caused by a [Bazel bug](https://github.com/bazelbuild/bazel/issues/4341) and the [workaround(https://github.com/grpc/grpc/pull/13929) was to define `GRPC_BAZEL_BUILD` when building gRPC.
Once the tests would build, they would run and fail due to …
> tests: make tests run on macOS/OS X

- start_esp/start_esp.py
In serverless  /var/log and /var/cache are mounted, need to make sure these two folders used by nginx are created.
> Make sure some key fordlers exists

- src/tools/BUILD
- src/tools/read_server_config.cc
- start_esp/start_esp.py
- start_esp/test/BUILD
- start_esp/test/start_esp_test.py
- start_esp/test/testdata/expected_grpc_backend_ssl_client_key_server.json
- start_esp/test/testdata/expected_grpc_backend_ssl_enable_server.json
- start_esp/test/testdata/expected_grpc_backend_ssl_root_certs_server.json
Added a c++ program to read the server_config json file generated by start_esp, to make sure the json format can be converted to server_config proto.
> Fix grpc_backend_ssl server_config format

- Jenkinsfile
- jenkins/slaves/Makefile
- jenkins/slaves/debian-9.Dockerfile
- nginx.bzl
- script/all-utilities
- script/linux-install-software
- script/tools/linux-install-docker
- script/tools/linux-install-gcc
- test/grpc/Dockerfile.temp
Jenkin test is broken.  The root cause is detailed in https://github.com/cloudendpoints/esp/pull/589
In this change:
1) update the slave image to debian9 (debian8 is outdated and gone). and run it as root
2) fix "t" test failure due to "run as root",  always run nginx as root in "t" tests
3) update the instruction to install docker to debian9
4) install gcc-4.9 to debian9 in order to run asan
> Fix Jenkins test

- src/nginx/grpc_finish.cc
- src/nginx/grpc_web_finish.cc
- src/nginx/t/grpc_interop_status.t
- src/nginx/t/grpc_web_interop_empty.t
- src/nginx/t/grpc_web_interop_status.t
- src/nginx/t/grpc_web_interop_unary.t
- src/nginx/util.cc
- src/nginx/util.h
- src/tools/BUILD
- src/tools/service_control_json_gen.cc
- test/grpc/interop-client.go
* call grpc internal function grpc_percent_encode
* add special_status_message test case for grpc interop test
* polish grpc_web_interop "t" tests to be more readable.
* add a message with space, to make sure it is encoded with %20.
> Percent encode for grpc tailer: grpc-message

- src/api_manager/auth/lib/BUILD
- src/api_manager/auth/lib/auth_jwt_validator.cc
- src/api_manager/auth/lib/auth_jwt_validator_test.cc
- src/nginx/t/auth_no_pkey.t
- src/nginx/t/auth_pkey.t
- src/nginx/t/auth_symmetrickey.t
- src/nginx/t/grpc_auth_pkey.t
- src/tools/BUILD
- src/tools/verify_token.cc
* Pass the detail error in the response for easy debugging.
* Add a tool verify_token to test token verification in a standalone environment.
> Improve JWT verification error reporting

- src/api_manager/proto/server_config.proto
- src/api_manager/service_control/aggregated.cc
- src/api_manager/service_control/aggregated.h
- src/nginx/t/BUILD
- src/nginx/t/check_network_failures.t
- src/nginx/t/test_timeout_retry.t
Service Control calls sometime may encounter long latency. It can be worked around by reducing timeout  with retries.
With this changes:  Here are the default timeout and retries
Check: timeout 1s and retries: 3 
Report:  timeout 2s and retries: 5
Quota: timeout 1s, and retries: 1
> Add retry for service control calls

- src/api_manager/proto/server_config.proto
- src/api_manager/service_control/aggregated.cc
Since SYN resend timeout is 1s.  Change the default time to allow at least one SYN resend
> Change default timeout

- src/nginx/t/grpc_web_interop_status.t
- src/nginx/util.cc
According to https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses
grpc percent encode reserved table is %x20-%x7E except "%".  So it should use grpc_compatible_percent_encoding_unreserved_bytes table
> Fix grpc percent encode reserved code table

- repositories.bzl
- src/api_manager/config_manager.cc
- src/api_manager/config_manager_test.cc
- src/api_manager/context/global_context.h
- src/api_manager/context/service_context.cc
- src/api_manager/service_control/aggregated.cc
- src/api_manager/service_control/aggregated.h
- src/api_manager/service_control/aggregated_test.cc
- src/nginx/t/BUILD
- src/nginx/t/config_rollouts_from_response.t
- src/nginx/t/config_rollouts_managed.t
Now the Check/Report response has service_rollout_id.  It can be used to reduce the periodical ESP calls to service_management service to check the latest rollout ID.
The checking interval is 1 minute. During the checking interval, if the service_rollout_id from Check/Report response is the same as the current used one.  Not need to make a HTTP call.
> Use the service_rollout_id from Check/Report response

- src/api_manager/service_control/proto.cc
- src/api_manager/service_control/testdata/final_report_request.golden
- src/api_manager/service_control/testdata/report_request.golden
- src/api_manager/service_control/testdata/report_request_by_consumer.golden
- src/api_manager/service_control/testdata/report_request_empty_optional.golden
- src/api_manager/service_control/testdata/report_request_failed.golden
- src/nginx/t/ServiceControl.pm
- src/nginx/t/grpc_api_key.t
- src/nginx/t/grpc_compression.t
- src/nginx/t/grpc_streaming.t
- src/nginx/t/grpc_uds.t
- src/nginx/t/multiple_apis.t
- src/nginx/t/testdata/grpc_echo_service.pb.txt
So querying endpoint log, publishers can find out ESP version and service config id used for each request.
It will be useful for debugging.
> Add service_agent and service_config_id to log_entries

- include/api_manager/api_manager.h
- src/api_manager/api_manager_impl.cc
- src/api_manager/config_manager.cc
- src/api_manager/config_manager.h
- src/api_manager/proto/api_manager_status.proto
- src/nginx/status.cc
- src/nginx/t/config_rollouts_from_response.t
Previous using number of actual calls to fake service_managment server is not stable. 
Instead adding some statistics to keep track of rollout calls.  and use the skipped_rollout_calls status
> Second try to fix flaky config_rollout_from_response test

- src/nginx/grpc.cc
- test/transcoding/bookstore-server.cc
When ESP creates grpc channel, need to increase grpc.max_metadata_size. This PR set it to INT_MAX
https://github.com/cloudendpoints/esp/issues/618
> Set grpc.max_metadata_size to INT_MAX

- WORKSPACE
https://github.com/grpc/grpc/pull/19114 is merged into grpc repo.  Now we can use the official one.
> Update grpc to use official repo not fork

- script/all-utilities
- script/linux-start-local-test
- script/linux-test-kb-long-run
The old secret files in client-secret-files bucket was removed by someone. The new secret files were re-created and uploaded to a new bucket
> Changed e2e tests to use new secret files

- start_esp/start_esp.py
Using a more unique filename for service config when using multiple services (`--experimental_enable_multiple_api_configs`) This fixes #641
> Using a more unique filename for storing service config files

- src/nginx/t/transcoding_deep_struct.t
Now, we can have comparison between a valid deep struct and an invalid deep struct. The first one is parsed successfully in ESP and is failed in the backend(500 Internal Server; too deep for the backend), while the second is failed in ESP directly(400 Bad Request; Not right format).
> [Transcoding] Fix Deep Struct T test

- src/nginx/module.cc
- src/nginx/module.h
- src/nginx/request.cc
Remove the cyclical construction between ngx_esp_request_ctx_s and NgxEspRequest.
> Replace ngx_http_esp_ensure_module_ctx with ngx_http_esp_get_module_ctx in request.cc

- include/api_manager/env_interface.h
- include/api_manager/periodic_timer.h
- src/api_manager/api_manager_test.cc
- src/api_manager/config_manager.cc
- src/api_manager/config_manager_test.cc
- src/api_manager/context/BUILD
- src/api_manager/context/client_ip_extraction_test.cc
- src/api_manager/mock_api_manager_environment.h
- src/api_manager/rewrite_rule_test.cc
- src/nginx/environment.cc
- src/nginx/environment.h
- start_esp/start_esp.py
NgxEspPeriodical timer object should not be freed in the timer callback function since Nginx is reading its data after the callback.
https://github.com/cloudendpoints/esp/pull/654  used that timer object as one time timer.  and free the object inside the callback fuction which cause the segment.
This changes:
* not to free the object,  only call stop, and wait for next time to override it
* add a new function IsStopped() to check if timer is still active
* Moved multiple MockPeriodTimer object into one place.
* Also seed the random generator.
> Fix crash: Not to free timer object in the timer callback function

- src/api_manager/api_manager_impl.cc
Such over-write will cause crash: the old object is released, but it may be used in async remote Check or Report call.  When the callback is called, it will use the freed object.
This will happen when: ESP starts with a service config with ID=A,  but rollout ID is unknown, or empty.  
When the a new rollout is detected,  fetching the config with the same ID=A,  it will over-write the old one.  It will cause crash
This crash bug exists long time ago. The trigger condition is:  --rollout_strategy=managed and --version is also set.  In this case, start_esp only fetch the specific version, set rollout_id to empty. 1 minutes after ESP started, it checks latest rollout, and fetch the config with same id, and replace the new ServiceContext with the old one.   If there are some on-going traffic …
> not to overwrite same config_id

- include/api_manager/method.h
- src/api_manager/method_impl.h
- src/api_manager/path_matcher.h
- src/api_manager/path_matcher_test.cc
- src/grpc/transcoding/transcoder_test.cc
- src/nginx/module.cc
- src/nginx/t/backend_routing_append_path.t
- src/nginx/t/backend_routing_constant_address.t
When x-google-backend is using CONSTANT_ADDRESS as path translation, if the query parameter has escaped characters, they will be unescaped when passing the request to the backend.
Issue: https://github.com/cloudendpoints/esp/issues/681
Also fixed a bug in module.cc where if uri doen't have query parameter, r.uri field is not changed.
> Escape query parameters in backend_routing

- start_esp/start_esp.py
This allows us to use a template that can leverage `${services}` rather than having to hardcode the list of multiple services when using `--experimental_enable_multiple_api_configs`.
> Add 2 more values to template vars to make multiple backend support better

- docker/serverless/Dockerfile.with_config
- docker/serverless/env-start-esp.py
- start_esp/start_esp.py
This PR just to get ESP code ready for building service config into serverless image
Separate pr will check in a script for users to build the image
1) Provide a docker file to build service config into docker
2) use flag --service_json_path to specify the service config, and enable it
> Get ready for building service config into serverless docker image

- test/echo/app_esp.yaml
There is another FLEX test: echo need to set readiness_check.  We are using "/version" for both.
> Fix e2e echo test failure

- start_esp/start_esp.py
It seems like "Set this flag to false to disable" should be "Set this flag to disable". It doesn't require additional args, such as true/false, but looks like it need one.
> fixed option description for disable sampling

- start_esp/fetch_service_config.py
Google service management API response body includes detail error message, such as
"error": {
"code": 403,
"message": "Service XYZ not found or permission denied.",
"status": "PERMISSION_DENIED"
}
}
It should be logged so users is better informed with the error.
> Log service config rollout fetching error

- src/api_manager/config_test.cc
- src/api_manager/method_impl.cc
- src/api_manager/method_test.cc
- src/nginx/t/backend_routing_constant_address.t
- src/nginx/t/testdata/bookstore_allow_all_http_requests.pb.txt
To fix: https://github.com/cloudendpoints/esp/issues/735
> Fix backend routing with CONSTANT_ADDRESS

- src/nginx/http.cc
- src/nginx/http.h
The code in src/nginx/http.{cc, h} is used to make side way Http call, such as fetching jwt public keys.  It is using Nginx upstream module with manually created connection and request object. 
After the response is received, esp finalize_request handler is called, ESP will process the response. 
and register a wakeup_event_handler to free the pools.  But Nginx will continue to call output filter chain, if any of them fail, the request and connection will be freed.  When wakeup_event_handler is called, it will try to access freed memory, it will crash.
In order to fix it,  esp_http_connection object is allocated its own esp_pool.  It will not be freed by connection and request.  It only be freed by wakeup_event_handler. It also detects if connection_pool or request_pool has been freed. …
> Fix ESP crash when fetching large jwt public keys

- src/grpc/proxy_flow.cc
- src/nginx/t/transcoding_metadata.t
ESP is calling grpc client to talk to backend grpc server.  The grpc client always append its "user-agent" header and overrides the original user-agent header.
Some applications need to use user-agent header.  
In this change, User-agent header is forwarded to the backend as  x-forwarded-user-agent.
> forward User-Agent header to grpc server as x-forwarded-user-agent

- src/api_manager/config.cc
- src/api_manager/config.h
- src/api_manager/config_test.cc
- test/transcoding/README.md
- test/transcoding/service.pb.txt
https://github.com/cloudendpoints/esp/issues/364
> Add support for Http rule additional_bindings

- script/e2e-kube.sh
- src/api_manager/api_manager_impl.cc
- src/api_manager/api_manager_impl.h
- src/api_manager/config_manager.cc
- src/api_manager/config_manager.h
- src/api_manager/config_manager_test.cc
- src/api_manager/proto/server_config.proto
- src/api_manager/service_control/aggregated.cc
- src/api_manager/service_control/aggregated.h
- src/api_manager/service_control/interface.h
- src/nginx/t/BUILD
- src/nginx/t/config_rollouts_by_timer.t
Sending an empty report to ServiceControl will be replied by the latest rollout ID.
Using this way to detect if service config rollout has been updated.
Update the e2e test, by not sending traffic to test if config has been updated.
> Periodically send empty report to detect rollout changes

- src/api_manager/config_manager.cc
- src/api_manager/config_manager.h
- src/nginx/t/config_rollouts_by_timer.t
Changes to fix https://github.com/cloudendpoints/esp/issues/773
> Fetch access token for rollout change timer

- src/api_manager/context/request_context.cc
- src/nginx/t/backend_routing_constant_address.t
For backend auth, before the header is overrided with ID token,  make a copy.
Some backend needs to to use it
> Copy the origin Authorization header to X-Forwarded-Authorization for backend_auth

- src/api_manager/service_control/aggregated.cc
- src/nginx/t/BUILD
- src/nginx/t/check_network_fail_open.t
- src/nginx/t/check_network_failures.t
- src/nginx/t/check_return_403.t
- src/nginx/t/failed_check.t
If ServiceControl  error response has body, it may contain important debug info, also pass that info to the client.
> Only apply network_fail_open policy to 5xx Http status code

- Jenkinsfile
- jenkins/slaves/Makefile
- script/linux-install-software
- start_esp/BUILD
- start_esp/fetch_service_config.py
- test/bookstore/swagger_template.json
As google-auth doesn't support python2.7 any more. 
But ESP has to stay with python2.7 since its bazel stay at 0.21.
> Rollback google auth

- src/grpc/zero_copy_stream.cc
- src/grpc/zero_copy_stream.h
- src/grpc/zero_copy_stream_test.cc
- src/nginx/t/transcoding_ignore_unknown_fields.t
- test/transcoding/README.md
- test/transcoding/bookstore-api.yaml
- test/transcoding/bookstore-server.cc
- test/transcoding/bookstore.proto
- test/transcoding/service.pb.txt
Fixes #795.
It is based on https://github.com/cloudendpoints/esp/pull/796
> Fix grpc transcoding bugs for unknown fields

- src/api_manager/fetch_metadata.cc
- src/nginx/t/metadata_timeout.t
b/148454048: GKE metadata server needs > 2s to fetch access token. 
Increase ESP access token fetching timeout to 5s (from 1s).
> Increase timeout of fetching access token from metadata server to 5s

- src/api_manager/fetch_metadata.cc
- src/nginx/t/ApiManager.pm
- src/nginx/t/metadata_timeout.t
- start_esp/fetch_service_config.py
b/148454048: GKE metadata server may take up to 30s to generate access token.
> Increase metadata fetch timeout to 30s

- Jenkinsfile
- script/e2e-kube.sh
- script/gke-e2e.sh
- script/jenkins-utilities
- test/bookstore/backend.yaml_temp
- test/grpc/grpc-interop.yaml
* remove "loose" gke tests.  They are not used in production any more.
* create a new gke deployment file in test/bookstore/backend.yaml_temp
*
> fix e2e tests: remove espcli in gke-e2e tests

- script/all-utilities
The old key was expired. Created a new key for service-control-in-load-test@esp-load-test.iam.gserviceaccount.com.
> Fix e2e test by switching to new SA key.

- src/api_manager/service_control/info.h
- src/api_manager/service_control/proto.cc
Propagates the API key UID when it is returned from CheckResponse.
> Propagates Api Key UID in ESP.

- start_esp/server-auto.conf.template
- start_esp/start_esp.py
- start_esp/test/start_esp_test.py
- start_esp/test/testdata/expected_client_ip_header_server.json
- start_esp/test/testdata/expected_client_ip_position_server.json
- start_esp/test/testdata/expected_cloud_trace_url_override_server.json
- start_esp/test/testdata/expected_compute_platform_override_server.json
- start_esp/test/testdata/expected_disable_cloud_trace_auto_sampling_server.json
- start_esp/test/testdata/expected_grpc_backend_ssl_client_key_server.json
- start_esp/test/testdata/expected_grpc_backend_ssl_enable_server.json
- start_esp/test/testdata/expected_grpc_backend_ssl_root_certs_server.json
- start_esp/test/testdata/expected_jwks_cache_duration.json
- start_esp/test/testdata/expected_management_server.json
- start_esp/test/testdata/expected_no_enable_api_key_uid_reporting.json
- start_esp/test/testdata/expected_redirect_authorization_url.json
- start_esp/test/testdata/expected_rewrite_server.json
- start_esp/test/testdata/expected_rollout_fetch_throttle_window.json
- start_esp/test/testdata/expected_rollout_strategy_server.json
- start_esp/test/testdata/expected_service_control_log_entries.json
- start_esp/test/testdata/expected_service_control_network_fail_open.json
- start_esp/test/testdata/expected_service_control_url_override_server.json
- start_esp/test/testdata/expected_transcoding_always_print_primitive_fields_server.json
- start_esp/test/testdata/expected_transcoding_preserve_proto_field_names_server.json
- Can pass`bazel test //start_esp/test:start_esp_test` 
- Built the image manually and manually checked ESPv1 with API key UUID change
> Default enable_api_key_uid_reporting to true
