cloudendpoints/esp

WORKSPACE, src/nginx/config.cc, src/nginx/module.cc, src/nginx/t/BUILD, src/nginx/t/config_rollouts_managed.t, src/nginx/t/init_service_configs_multiple.t, src/nginx/t/init_service_configs_single.t
- ServiceConfigRollout in  server_config.proto
- Check service config loading using ApiManager.LoadServiceRollouts()
- Added t test for service configs update using rollouts
=> Applied latest changes of ApiManager

WORKSPACE
Use NGINX that doesn't limit the number of requests per HTTP/2 connection
=> Update NGINX to fix gRPC e2e tests.

script/create-test-env-json
Fixes perf test.
See:
https://endpoints-jenkins.appspot.com/job/esp/job/postsubmits-master/167/execution/node/510/log/
=> Fix create-test-env-json

WORKSPACE, repositories.bzl, src/api_manager/auth/lib/auth_jwt_validator.cc, src/api_manager/auth/lib/auth_token.cc, src/api_manager/auth/lib/grpc_internals.h, src/grpc/message_serializer.cc, src/grpc/proxy_flow.cc, src/grpc/proxy_flow.h, src/grpc/zero_copy_stream_test.cc, src/nginx/grpc_passthrough_server_call.cc, src/nginx/grpc_passthrough_server_call.h, src/nginx/grpc_server_call.cc, src/nginx/grpc_server_call.h, src/nginx/main/BUILD, src/nginx/t/ApiManager.pm, src/nginx/t/BUILD, src/nginx/t/grpc_api_key.t, src/nginx/t/grpc_compression.t, src/nginx/t/grpc_interop_ministress.t, src/nginx/t/grpc_streaming.t, src/nginx/t/grpc_uds.t, src/nginx/transcoded_grpc_server_call.cc, src/nginx/transcoded_grpc_server_call.h, test/grpc/client-test-lib.cc, test/grpc/repositories.bzl
Almost reverse of #187 and istio/proxy#340 .
=> Update gRPC to 1.4.2

Jenkinsfile, WORKSPACE, repositories.bzl, script/jenkins-utilities, src/nginx/main/BUILD, src/nginx/main/testdata/data-expected, test/bookstore/gce/e2e.sh, test/docker/docker_test.sh, test/docker/docker_test_lib.sh, test/docker/esp_generic/custom_nginx.conf, test/docker/management/Dockerfile, test/docker/management/management.js, test/docker/management/rollouts.json, test/docker/management/service.2017-05-15r0.json, test/docker/management/service.2017-05-16r0.json, test/docker/management/service.json, test/docker/metadata/metadata.js
This is recovery of the PR 230
=> Added service config auto rollouts e2e test for GCE

src/nginx/t/config_rollouts_managed.t
Triggers the first config rollouts update after the first /endpoints_status call to remove the lace condition
=> Improved stability of config_rollouts_managed.t

WORKSPACE, src/nginx/main/BUILD, src/nginx/main/ngx_modules.c
This adds functionality that is part of larger system that allows IAP's signed JWTs to be verified automatically on App Engine Flex VMs.
=> Integrate IAP JWT auto-verification for GAE Flex

src/nginx/status.cc
ngx_worker contains the worker number.
http://hg.nginx.org/nginx/rev/b4cc553aafeb
=> Used ngx_worker to access shared memory for stats

script/linux-test-kb-long-run, script/linux-test-vm-bookstore, test/client/esp_h2load_runner.py, tools/src/t/bookstore.go
Bug: https://buganizer.corp.google.com/issues/65880499
=> Remove verbose flag

src/nginx/t/unregistered.t, src/nginx/t/unregistered_no_project.t
Timing caused report batch to write 1 or 2 reports.  But test expects one report.  Hence the test is flaky
Disable cache for Check and Report.
=> Fix flaky unregister.t tests

include/api_manager/api_manager.h, src/api_manager/api_manager_impl.cc, src/api_manager/api_manager_impl.h, src/api_manager/api_manager_test.cc, src/api_manager/proto/server_config.proto, src/nginx/module.cc, src/nginx/module.h, src/nginx/t/BUILD, src/nginx/t/api_basepath.t, src/nginx/t/api_basepath_hard_match.t
This is the recovery for the PR #287, the fork repository was accidentally deleted.
=> ESP supports API basepath

include/api_manager/api_manager.h, src/api_manager/api_manager_impl.h, src/api_manager/context/global_context.h, src/api_manager/proto/server_config.proto, src/grpc/transcoding/transcoder_factory.cc, src/grpc/transcoding/transcoder_factory.h, src/nginx/module.cc
@lizan, here the PR for master as requested.
=> Added always_print_primitive_fields experimental option (#227)

src/nginx/t/BUILD
Remove a flaky test grpc_interop_ministress
=> Remove a flaky test grpc_interop_ministress

BUILD, Jenkinsfile, WORKSPACE, repositories.bzl, src/nginx/main/testdata/copyright-expected, src/nginx/t/grpc_api_key.t, src/nginx/t/grpc_compression.t, src/nginx/t/grpc_streaming.t, src/nginx/t/grpc_uds.t, test/grpc/BUILD, test/grpc/client-test-lib.cc, test/grpc/repositories.bzl, tools/src/BUILD
This reverts commit 016d0f568ebe45688e91d791bf9069f33f77dff4.
To see if this stabilize test infra. Will do upgrade in another PR.
=> Revert "Upgrade gRPC to v1.6.0 (#256)"

Jenkinsfile, src/nginx/t/BUILD
(For diagnosing Jenkins presubmit tests only) tune Jenkins config
=> Temporarily disable tsan and asan presubmit tests

include/api_manager/utils/status.h, src/api_manager/utils/status.cc, src/nginx/error.cc, src/nginx/module.h, src/nginx/t/transcoding_errors.t, src/nginx/transcoded_grpc_server_call.cc, test/transcoding/BUILD, test/transcoding/bookstore-server.cc
Which issue this PR fixes: fixes #204
=> support "grpc-status-details-bin"

script/robot-release, start_esp/debug_nginx.sh
The debug binary file was copied into a wrong place.
=> Copy nginx-debug image into right place

src/nginx/http.cc
=> Harden code, not to free nullptr pool

WORKSPACE, repositories.bzl, src/api_manager/auth/lib/auth_jwt_validator.cc, src/api_manager/auth/lib/auth_token.cc, src/api_manager/auth/lib/grpc_internals.h, src/grpc/proxy_flow.cc, src/grpc/zero_copy_stream_test.cc, src/nginx/grpc_passthrough_server_call.cc, src/nginx/grpc_queue.h, src/nginx/grpc_server_call.cc, src/nginx/grpc_server_call.h, src/nginx/http.cc, src/nginx/main/BUILD, src/nginx/main/testdata/copyright-expected, src/nginx/t/grpc_api_key.t, src/nginx/t/grpc_compression.t, src/nginx/t/grpc_downstream_flow_control.t, src/nginx/t/grpc_streaming.t, src/nginx/t/grpc_uds.t, src/nginx/t/grpc_upstream_flow_control.t, src/nginx/transcoded_grpc_server_call.cc, test/grpc/client-test-lib.cc
The gRPC version was from Jun 2017.
=> Upgrade gRPC from 1.4.2 to 1.15.0

src/nginx/http.cc
https://github.com/cloudendpoints/esp/issues/452
=> change side-way http to use 1.1

script/linux-install-software, script/presubmits, script/robot-presubmit, start_esp/start_esp.py, start_esp/test/testdata/expected_cors_allow_credentials_nginx.conf, start_esp/test/testdata/expected_cors_allow_headers_nginx.conf, start_esp/test/testdata/expected_cors_allow_methods_nginx.conf, start_esp/test/testdata/expected_cors_allow_origin_nginx.conf, start_esp/test/testdata/expected_cors_allow_origin_regex_nginx.conf, start_esp/test/testdata/expected_cors_expose_headers_nginx.conf, start_esp/test/testdata/expected_cors_preset_basic_nginx.conf
Fix errors of start_esp tests and enable start_esp tests in presubmit tests
=> Fix errors of start_esp tests and enable start_esp tests in presubmit tests

doc/k8s/README.md, doc/tutorial.md, script/e2e-kube.sh, script/jenkins-tests-cleanup.sh, script/jenkins-utilities, script/linux-start-local-test, test/grpc/local/README.md
Fix e2e test errors caused by gcloud commands.
=> Fix e2e test errors

start_esp/nginx-auto.conf.template, start_esp/start_esp.py, start_esp/test/start_esp_test.py
So it can be removed if deem to.
=> add experimental prefix for flag proxy_backend_host_header

start_esp/nginx-auto.conf.template, start_esp/test/testdata/expected_cors_allow_credentials_nginx.conf, start_esp/test/testdata/expected_cors_allow_headers_nginx.conf, start_esp/test/testdata/expected_cors_allow_methods_nginx.conf, start_esp/test/testdata/expected_cors_allow_origin_nginx.conf, start_esp/test/testdata/expected_cors_allow_origin_regex_nginx.conf, start_esp/test/testdata/expected_cors_expose_headers_nginx.conf, start_esp/test/testdata/expected_cors_preset_basic_nginx.conf, start_esp/test/testdata/expected_enable_strict_transport_security_nginx.conf
Move strict_tls_security header from server level to location level.
=> Move strict_tls_security header from server level to location level

src/nginx/http.cc
=> Increase side-way http maximum response side

src/nginx/grpc_web_finish.cc, src/nginx/t/grpc_web_interop_unary.t
If grpc sending trailers, grpc_web code crashes.
=> Fix grpc_web crash at sending trailers

CHANGELOG.md
=> Update CHANGELOG for 1.27.0

src/api_manager/auth/lib/auth_jwt_validator.cc
In certain cases,  e.g. "kid" is not specified in the JWT header,  ESP needs to try all public keys in the JWKS.  Some of them will fail.  Not to log such failure to cause users fault alarm.
=> Not log JWT error when trying multiple public keys

start_esp/start_esp.py, start_esp/test/start_esp_test.py
Using the flag with most other flags is disabled.
=> Add --enable_backend_routing flag.

doc/testing.md, start_esp/nginx-auto.conf.template, start_esp/test/testdata/expected_access_log_nginx.conf, start_esp/test/testdata/expected_allow_invalid_headers_nginx.conf, start_esp/test/testdata/expected_backend_host_header_nginx.conf, start_esp/test/testdata/expected_backend_nginx.conf, start_esp/test/testdata/expected_backend_routing_nginx.conf, start_esp/test/testdata/expected_basic_nginx.conf, start_esp/test/testdata/expected_client_body_buffer_size_nginx.conf, start_esp/test/testdata/expected_client_max_body_size_nginx.conf, start_esp/test/testdata/expected_cors_allow_credentials_nginx.conf, start_esp/test/testdata/expected_cors_allow_headers_nginx.conf, start_esp/test/testdata/expected_cors_allow_methods_nginx.conf, start_esp/test/testdata/expected_cors_allow_origin_nginx.conf, start_esp/test/testdata/expected_cors_allow_origin_regex_nginx.conf, start_esp/test/testdata/expected_cors_expose_headers_nginx.conf, start_esp/test/testdata/expected_cors_preset_basic_nginx.conf, start_esp/test/testdata/expected_dns_nginx.conf, start_esp/test/testdata/expected_enable_debug_nginx.conf, start_esp/test/testdata/expected_enable_strict_transport_security_nginx.conf, start_esp/test/testdata/expected_enable_websocket_nginx.conf, start_esp/test/testdata/expected_experimental_enable_multiple_api_configs_disabled_nginx.conf, start_esp/test/testdata/expected_healthz_nginx.conf, start_esp/test/testdata/expected_metadata_nginx.conf, start_esp/test/testdata/expected_ssl_port_nginx.conf, start_esp/test/testdata/expected_ssl_protocols_nginx.conf, start_esp/test/testdata/expected_status_port_nginx.conf, start_esp/test/testdata/expected_underscores_in_headers_nginx.conf, start_esp/test/testdata/expected_worker_processes_nginx.conf
- Remove backslash before $backend_url
- Add resolver under server
=> Modify Nginx config template

include/api_manager/response.h, src/api_manager/context/request_context.cc, src/api_manager/context/request_context.h, src/api_manager/proto/server_config.proto, src/api_manager/service_control/info.h, src/api_manager/service_control/proto.cc, src/nginx/response.cc, src/nginx/response.h, src/nginx/t/BUILD, src/nginx/t/report_with_headers.t, src/nginx/util.cc, src/nginx/util.h, start_esp/server-auto.conf.template, start_esp/start_esp.py, start_esp/test/BUILD, start_esp/test/start_esp_test.py, start_esp/test/testdata/expected_service_control_report_http_headers.json
requested by https://github.com/cloudendpoints/esp/issues/489
=> log http request and response headers if configured

src/grpc/proxy_flow.cc
To fix https://github.com/cloudendpoints/esp/issues/560
=> Not to send connection headers to gRPC upstream

README.md, script/release-publish
Also changed release-publish to publish the secure image
=> Update 4 secure

start_esp/start_esp.py, start_esp/test/start_esp_test.py
* Remove the reference to DEFAULT_LARGE_CLIENT_HEADER_BUFFERS
* Add more tests in start_esp_test.py
=> Fix the crash from undefined reference in start_esp.py

repositories.bzl, src/api_manager/service_control/proto.cc, src/nginx/t/BUILD, src/nginx/t/check_api_target_blocked.t
=>  Handle API_TARGET_BLOCKED and RESOURCE_EXHAUSTED

src/api_manager/auth/lib/auth_jwt_validator.cc, src/api_manager/auth/lib/auth_jwt_validator_test.cc, src/api_manager/auth/lib/auth_token_test.cc, src/api_manager/auth/lib/json_test.cc, src/api_manager/auth/lib/json_util.cc, src/api_manager/http_template.cc, src/api_manager/http_template.h, src/api_manager/http_template_test.cc, src/api_manager/rewrite_rule.cc, src/grpc/zero_copy_stream_test.cc
These are detected by 
bazel test --config=asan
=> Fix some memory leak in unit tests

repositories.bzl
With removed log when existing.
=> Update to latest service control client lib

script/release-show
1) Add a new script "script/release-show" to show the docker image and rapture 
2) modify script/release-stable to add-tag for the docker images.
=> Update release scripts

WORKSPACE, repositories.bzl, src/api_manager/config.cc, src/api_manager/config_test.cc, third_party/BUILD
Also fixed the hack of using fork for googleapis.
Update servicecontrol_client to latest
=> Update Nginx to 1.15.9

CHANGELOG.md
Changelog for the release 1.35.0
=> Changelog for the release 1.35.0

start_esp/nginx-auto.conf.template, start_esp/test/testdata/expected_access_log_nginx.conf, start_esp/test/testdata/expected_allow_invalid_headers_nginx.conf, start_esp/test/testdata/expected_backend_host_header_nginx.conf, start_esp/test/testdata/expected_backend_nginx.conf, start_esp/test/testdata/expected_backend_routing_nginx.conf, start_esp/test/testdata/expected_basic_nginx.conf, start_esp/test/testdata/expected_client_body_buffer_size_nginx.conf, start_esp/test/testdata/expected_client_max_body_size_nginx.conf, start_esp/test/testdata/expected_cors_allow_credentials_nginx.conf, start_esp/test/testdata/expected_cors_allow_headers_nginx.conf, start_esp/test/testdata/expected_cors_allow_methods_nginx.conf, start_esp/test/testdata/expected_cors_allow_origin_nginx.conf, start_esp/test/testdata/expected_cors_allow_origin_regex_nginx.conf, start_esp/test/testdata/expected_cors_expose_headers_nginx.conf, start_esp/test/testdata/expected_cors_preset_basic_nginx.conf, start_esp/test/testdata/expected_dns_nginx.conf, start_esp/test/testdata/expected_enable_debug_nginx.conf, start_esp/test/testdata/expected_enable_strict_transport_security_nginx.conf, start_esp/test/testdata/expected_enable_websocket_nginx.conf, start_esp/test/testdata/expected_experimental_enable_multiple_api_configs_disabled_nginx.conf, start_esp/test/testdata/expected_healthz_nginx.conf, start_esp/test/testdata/expected_large_client_header_buffers_nginx.conf, start_esp/test/testdata/expected_metadata_nginx.conf, start_esp/test/testdata/expected_server_config_dir_nginx.conf, start_esp/test/testdata/expected_ssl_port_nginx.conf, start_esp/test/testdata/expected_ssl_protocols_nginx.conf, start_esp/test/testdata/expected_status_port_nginx.conf, start_esp/test/testdata/expected_underscores_in_headers_nginx.conf, start_esp/test/testdata/expected_worker_processes_nginx.conf
https://github.com/cloudendpoints/esp/issues/630
=> Allow nginx config to include other custom configs

src/api_manager/context/request_context.cc, src/api_manager/method_impl.cc, src/nginx/t/backend_routing_append_path.t
If backend type is APPEND,  path is not modified.  But if backend_address has a path, it should be append.
https://github.com/cloudendpoints/esp/issues/637
=> Fix backend address with path

src/api_manager/check_auth.cc, src/api_manager/check_auth_test.cc
https://github.com/cloudendpoints/esp/issues/652
=> Allow JWT from authorization without Bearer prefix

doc/tutorial.md
=> Fix typo on tutorial.md

include/api_manager/request_handler_interface.h, src/api_manager/context/request_context.cc, src/api_manager/context/request_context.h, src/api_manager/request_handler.cc, src/api_manager/request_handler.h, src/nginx/grpc.cc, src/nginx/t/transcoding_metadata.t
https://github.com/cloudendpoints/esp/issues/363
=> Add api-key to Header when doing json-grpc transcoding

src/nginx/t/metadata.t, src/nginx/t/quota_exhausted.t
metadata.t and quota_exhaused.t  are flaky due to service control cache.
=> disable service control cache for two flaky t tests

src/api_manager/fetch_metadata.cc, src/nginx/t/backend_routing_constant_address.t
https://github.com/cloudendpoints/esp/issues/675
=> Change metadata token request url for getting full JWT

CHANGELOG.md
=> Change log update for 1.40.0

docker/serverless/Dockerfile.with_config, docker/serverless/gcloud_build_image
Users will run this script.  Will update the Cloud Run doc to add a step.
=> Upload a script to build service config into image for serverless

src/nginx/http.cc, src/nginx/http.h
Reverts cloudendpoints/esp#745
=> Revert "Fix ESP crash when fetching large jwt public keys"

src/nginx/http.cc, src/nginx/http.h
It was reverted by cloudendpoints/esp#746
Now resubmit it
=> Re-submit "Fix ESP crash when fetching large jwt public keys"

script/validate_release.py
docker-tests has been abandoned so remove it in the release-validation.
=> Remove abandoned test check

docker/generic/Dockerfile
=> replace docker base with debian:buster

CHANGELOG.md
=> Update changelog for release 1.51.0

script/jenkins-utilities, start_esp/BUILD
To fix 
b/159130561: oauth2client is not working again
b/159130643: E2E test script set_esp_service_version is not working
Not sure if the first part will work.  Will use pre-e2e test to verify it
=> Fix e2e test

src/api_manager/config.cc
=> Change to warning for duplicated http options template

script/all-utilities, test/grpc/gke/interop.yaml.temp
=> fix e2e tests: flex and gke interop

repositories.bzl, src/api_manager/service_control/check_response_test.cc, src/api_manager/service_control/proto.cc, src/api_manager/utils/marshalling.cc
=> update googleapis to the 05/18/2021

script/linux-start-local-test
=> fix local performance test

script/validate_release.py
=> remove two loose e2e tests from validate_release.py

CHANGELOG.md
=> Update CHANGELOG for 1.57.0

WORKSPACE, nginx_build.bzl
=> fix broken build replace pcre downloading url

src/api_manager/path_matcher_node.cc, src/api_manager/path_matcher_test.cc
=> Fix path_matcher not to make recursive calls

script/all-utilities
=> fix flex e2e test

script/linux-start-local-test
=> fix performace test
